### PR TITLE
Cleaned Feature more filter functions revised (#23)

### PR DESCRIPTION
**Pull request by mielvds**
This is a cleaned version of #23

### CODE REVIEW

**Comment by RubenVerborgh** [comment]
@mielvds I reviewed this and would merge as [feature-more-filters](https://github.com/LinkedDataFragments/Client.js/tree/feature-more-filters). Can you confirm?

PS Threw out the crypto stuff for now because it didn't work.

**Comment by mielvds** [comment]
Fine by me, except:
- what was wrong with the crypto? (Never tested this though)
- not too happy with the disappearance of the unimplemented functions.  Everything from the spec was in there, now we have to remember which ones are missing. Also, without UnimplementedOperatorError, we'll have to keep explaining to people that our implementation is not spec compliant.
- why no REPLACE flags?
- are the unittests complete? Haven't checked this in detail

**Comment by RubenVerborgh** [comment]
> what was wrong with the crypto? (Never tested this though)

I really didn't work. Threw something like "MD5 is not a function". The API of the cryptojs module is totally different.

> not too happy with the disappearance of the unimplemented functions. Everything from the spec was in there, now we have to remember which ones are missing.

I can make comments for them.
(Should always be careful about size given that this goes to browsers.)

> Also, without UnimplementedOperatorError, we'll have to keep explaining to people that our implementation is not spec compliant.

I'll change the default error to "Not implemented".

> why no REPLACE flags?

The code assumed that `String#replace` had a flags parameter in JavaScript, but it doesn't. So flags would silently fail; this makes it explicit.

> are the unittests complete?

I think so, will double-check.

**Comment by mielvds** [comment]
> The code assumed that String#replace had a flags parameter in JavaScript, but it doesn't. So flags would silently fail; this makes it explicit.

Ah yes, It should have been something like `replace('/'+ a +'/' + flags, b)`

**Comment by RubenVerborgh** [comment]
Thanks a lot, merged as 4aafe0b2b510a388cdf1a102877c63bdae004262.

**Comment by RubenVerborgh** [comment]
Had to unmerge because of problems with the argument checking. In the old engine, we could have:
```
50 > 100 // true (correct)
"50" > "100" // false (incorrect)
```

In the new engine, we have:
```
50 > 100 // true (correct)
"50" > "100" // deliberately throws type error
```

Unfortunately, the latter case also occurs [in benchmarks](http://lists.w3.org/Archives/Public/public-sparql-dev/2017JanMar/0001.html), and would break our compatibility with them. As such, we should not merge before this is fixed. (In general, all FedBench queries should return the correct number of results before we merge.) Code still available as [feature-more-filters](https://github.com/LinkedDataFragments/Client.js/tree/feature-more-filters).

**Comment by rubensworks** [comment]
Thanks for the PR, but this project has now been deprecated in favor of [Comunica](https://github.com/comunica/comunica).

**Pull request closed without merging**
